app1/urls.py
from django.urls import path
from . import views

app_name='app1'

urlpatterns = [
    path('',views.hola,name='hola'),
    path('primerhtml',views.primerhtml,name='primerhtml'),
    path('segundohtml',views.segundohtml,name='segundohtml')
]

app2/urls.py
from django.urls import path
from . import views

app_name='app2'

urlpatterns = [
    path('',views.inicio,name='inicio'),
    path('nuevoRegistro',views.nuevoRegistro,name='nuevoRegistro'),
    path('nuevaArea',views.nuevaArea,name='nuevaArea'),
    path('usuarios',views.usuarios,name='usuarios'),
    path('areas',views.areas,name='areas'),
    path('verArea/<str:idArea>',views.verArea,name='verArea')
]

miPrimerProyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    path('',include('app3.urls'))
]

app2/models.py
from django.db import models

class area(models.Model):
    nombreArea = models.CharField(max_length=32, null=True, blank=True)
    descripcionArea = models.CharField(max_length=256, null=True, blank=True)

# Create your models here.
class usuario(models.Model):
    nombreUsuario = models.CharField(max_length=64, null=True, blank=True)
    numeroUsuario = models.CharField(max_length=32, null=True, blank=True)
    direccionUsuario = models.CharField(max_length=64, null=True, blank=True)
    areaUsuario = models.CharField(max_length=32, null=True, blank=True)
    descripcionUsuario = models.CharField(max_length=256, null=True, blank=True)
    areaR = models.ForeignKey(area, null=True, blank=True, on_delete=models.SET_NULL)

app2/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import usuario,area


# Create your views here.
def inicio(request):
    return render(request,'inicio.html')

def nuevoRegistro(request):
    if request.method == 'POST':
        nombreUsuario = request.POST.get('nombreUsuario')
        numeroUsuario = request.POST.get('numeroUsuario')
        direccionUsuario = request.POST.get('direccionUsuario')
        areaSeleccionada = request.POST.get('areaSeleccionada')
        areaObj = area.objects.get(id=areaSeleccionada)
        usuario.objects.create(
            nombreUsuario=nombreUsuario,
            numeroUsuario=numeroUsuario,
            direccionUsuario=direccionUsuario,
            areaR=areaObj
        )
        return HttpResponseRedirect(reverse('app2:usuarios'))
    return render(request,'nuevoRegistro.html',{
        'areasSistema':area.objects.all()
    })

def nuevaArea(request):
    if request.method == 'POST':
        nombreArea = request.POST.get('nombreDireccion')
        descripcionArea = request.POST.get('descripcionDireccion')
        area.objects.create(
            nombreArea=nombreArea,
            descripcionArea=descripcionArea
        )
        return HttpResponseRedirect(reverse('app2:areas'))
    return render(request,'nuevaArea.html',{
        'areasSistema':area.objects.all()
    })

def usuarios(request):
    usuariosTotales = usuario.objects.all()
    return render(request,'usuarios.html',{
        'usuariosTotales':usuariosTotales,
        'areasSistema':area.objects.all()
    })

def areas(request):
    areasTotales = area.objects.all()
    return render(request,'areas.html',{
        'areasTotales':areasTotales,
        'areasSistema':area.objects.all()
    })

def verArea(request,idArea):
    areaInfo = area.objects.get(id=idArea)
    listaUsuarios = areaInfo.usuario_set.all()
    return render(request,'verArea.html',{
        'objArea':areaInfo,
        'areasSistema':area.objects.all(),
        'listaUsuarios':listaUsuarios
    })

app2/templates/areas.html
{% extends "layout.html" %}

{% block titulo %}
    Areas registrados
{% endblock %}

{% block contenido %}
    <h2>Lista de areas</h2>
    <ol>
        {% for areaInfo in areasTotales %}
        <br>
        <li>
            <ul>
                <li>Nombre : {{ areaInfo.nombreArea }}</li>
                <li>Descripcion : {{ areaInfo.descripcionArea }}</li>
            </ul>
        </li>
        {% endfor %}
    </ol>
{% endblock %}

app2/templates/inicio.html
{% extends "layout.html" %}

{% block titulo %}
    Directorio
{% endblock %}

{% block contenido %}
    Pagina principal del directorio
{% endblock %}

app2/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block titulo %}{% endblock %}</title>
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    </head>
    <body>
        <div class="row">
            <div class="col-3">
                <h2>Directorio</h2>
                <div>
                    <a href="{% url 'app2:inicio' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'app2:nuevoRegistro' %}">Crear nuevo registro</a>
                </div>
                <div>
                    <a href="{% url 'app2:nuevaArea' %}">Crear nueva area</a>
                </div>
                <div>
                    <a href="{% url 'app2:usuarios' %}">Usuarios</a>
                </div>
                <div>
                    <a href="{% url 'app2:areas' %}">Areas</a>
                </div>
                <br>
                {% for areaInfo in areasSistema %}
                <div>
                    <a href="{% url 'app2:verArea' areaInfo.id %}">Ver {{ areaInfo.nombreArea }}</a>
                </div>
                {% endfor %}
            </div>
            <div class="col-9">
                {% block contenido %}

                {% endblock %}
            </div>
        </div>
    </body>
</html>

app2/templates/nuevaArea.html
{% extends "layout.html" %}

{% block titulo %}
    Nueva Area
{% endblock %}

{% block contenido %}
<h2>Crear nueva area</h2>
<form class="row" method="post" action="{% url 'app2:nuevaArea' %}">
    {% csrf_token %}
    <div>
        <label>Ingrese nombre</label>
        <input type="text" name="nombreDireccion">
    </div>
    <div>
        <label>Ingrese descripcion</label>
        <input type="text" name="descripcionDireccion">
    </div>
    <div>
        <input type="submit" value="Registrar">
    </div>
</form>
{% endblock %}

app2/templates/nuevoRegistro.html
{% extends "layout.html" %}

{% block titulo %}
    Nuevo Registro
{% endblock %}

{% block contenido %}
    <h2>Crear nuevo usuario</h2>
    <form class="row" method="post" action="{% url 'app2:nuevoRegistro' %}">
        {% csrf_token %}
        <div>
            <label>Ingrese nombre</label>
            <input type="text" name="nombreUsuario">
        </div>
        <div>
            <label>Ingrese numero</label>
            <input type="text" name="numeroUsuario">
        </div>
        <div>
            <label>Ingrese direccion</label>
            <input type="text" name="direccionUsuario">
        </div>
        <div>
            <label>Seleccionar area</label>
            <select name="areaSeleccionada">
                {% for areaInfo in areasSistema %}
                <option value="{{ areaInfo.id }}">{{ areaInfo.nombreArea }}</option>
                {% endfor %}
            </select>
        </div>
        <div>
            <input type="submit" value="Registrar">
        </div>
    </form>
{% endblock %}

app2/templates/usuarios.html
{% extends "layout.html" %}

{% block titulo %}
    Usuarios registrados
{% endblock %}

{% block contenido %}
    <h2>Lista de usuarios</h2>
    <ol>
        {% for usuarioInfo in usuariosTotales %}
        <br>
        <li>
            <ul>
                <li>Nombre : {{ usuarioInfo.nombreUsuario }}</li>
                <li>Telefono : {{ usuarioInfo.numeroUsuario }}</li>
                <li>Direccion : {{ usuarioInfo.direccionUsuario }}</li>
                <li>Area : {{ usuarioInfo.areaR.nombreArea }}</li>
            </ul>
        </li>
        {% endfor %}
    </ol>
{% endblock %}

app2/templates/verArea.html
{% extends "layout.html" %}

{% block titulo %}
    Area : {{ objArea.nombreArea }}
{% endblock %}

{% block contenido %}
<h2>AREA : {{ objArea.nombreArea }}</h2>
<div>
    <h4>LISTA DE USUARIOS</h4>
    {% for usuarioInfo in listaUsuarios %}
    <div>
        <ul>
            <li>{{ usuarioInfo.nombreUsuario }}</li>
            <li>{{ usuarioInfo.numeroUsuario }}</li>
        </ul>
    </div>
    <br>
    {% endfor %}
</div>
{% endblock %}