app1/urls.py
from django.urls import path
from . import views

app_name='app1'

urlpatterns = [
    path('',views.hola,name='hola'),
    path('primerhtml',views.primerhtml,name='primerhtml'),
    path('segundohtml',views.segundohtml,name='segundohtml')
]

app3/urls.py
from django.urls import path
from . import views

app_name='app3'

urlpatterns = [
    path('',views.ingresoUsuario,name='ingresoUsuario'),
    path('informacionUsuario',views.informacionUsuario,name='informacionUsuario'),
    path('cerrarSesion',views.cerrarSesion,name='cerrarSesion'),
    path('ejemploJs',views.ejemploJs,name='ejemploJs'),
    path('devolverDatos',views.devolverDatos,name='devolverDatos'),
    path('devolverAllPubs',views.devolverAllPubs,name='devolverAllPubs'),
    path('devolverPublicacion',views.devolverPublicacion,name='devolverPublicacion'),
    path('publicarComentario',views.publicarComentario,name='publicarComentario'),
    path('crearPublicacion', views.crearPublicacion, name='crearPublicacion'),
    path('inicioReact', views.inicioReact, name='inicioReact'),
    path('eliminarPublicacion', views.eliminarPublicacion, name='eliminarPublicacion'),
    
    #RUTA CONSOLA ADMINISTRADOR - EXAMEN FINAL
    path('consolaAdministrador',views.consolaAdministrador,name='consolaAdministrador'),
    #RUTA ACTUALIZARUSUARIO, OBTENERDATOSUSUARIO - EXAMEN FINAL
    path('obtenerDatosUsuario',views.obtenerDatosUsuario,name='obtenerDatosUsuario'),
    path('actualizarUsuario',views.actualizarUsuario,name='actualizarUsuario')

]

miPrimerProyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    path('',include('app3.urls'))
]

app3/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class datosUsuario(models.Model):
    profesion = models.CharField(max_length=48,null=True,blank=True)
    nroCelular = models.CharField(max_length=16,null=True,blank=True)
    perfilUsuario = models.CharField(max_length=256,null=True,blank=True)
    usrRel = models.OneToOneField(User,null=True,blank=True,on_delete=models.CASCADE)

class publicacion(models.Model):
    titulo = models.CharField(max_length=64,null=True,blank=True)
    descripcion = models.CharField(max_length=256,null=True,blank=True)
    autorPub = models.ForeignKey(User,on_delete=models.CASCADE, null=True, blank=True)
    imagenPub = models.ImageField(upload_to='imagenes/',null=True, blank=True)

class comentario(models.Model):
    descripcion = models.CharField(max_length=256,null=True,blank=True)
    pubRel = models.ForeignKey(publicacion, on_delete=models.CASCADE, null=True, blank=True)
    autoCom = models.ForeignKey(User,on_delete=models.CASCADE, null=True, blank=True)

app3/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, JsonResponse, FileResponse
from django.urls import reverse
from .models import publicacion, comentario, datosUsuario
import json
import base64
from django.contrib.auth.models import User

# -- Ingreso y cierre de sesión del usuario --

def ingresoUsuario(request):
    if request.method == 'POST':
        nombreUsuario = request.POST.get('nombreUsuario')
        contraUsuario = request.POST.get('contraUsuario')
        usrObj = authenticate(request, username = nombreUsuario, password = contraUsuario)
        if usrObj is not None:
            login(request,usrObj)
            return HttpResponseRedirect(reverse('app3:informacionUsuario'))
        else:
            return HttpResponseRedirect(reverse('app3:ingresoUsuario'))
    return render(request,'ingresoUsuario.html')

@login_required(login_url='/')
def cerrarSesion(request):
    logout(request)
    return render(request,'ingresoUsuario.html')

# -- Información del usuario --

@login_required(login_url='/')
def informacionUsuario(request):
    return render(request,'informacionUsuario.html',{
        'allPubs':publicacion.objects.all()
    })

def devolverAllPubs(request):
    objPub = publicacion.objects.all()
    listaPublicacion = []
    for obj in objPub:
        listaPublicacion.append(
            {
                'titulo':obj.titulo,
                'descripcion':obj.descripcion
            }
        )
    return JsonResponse({
        'listaPublicacion':listaPublicacion
    })

def devolverPublicacion(request):
    idPub = request.GET.get('idPub')
    try:
        datosComentarios = []
        objPub = publicacion.objects.get(id=idPub)
        comentariosPub = objPub.comentario_set.all()
        for comentarioInfo in comentariosPub:
            datosComentarios.append({
                'autor': f"{comentarioInfo.autoCom.first_name} {comentarioInfo.autoCom.last_name}",
                'descripcion': comentarioInfo.descripcion
            })
        try:
            with open(objPub.imagenPub.path,'rb') as imgFile:
                imgPub = base64.b64encode(imgFile.read()).decode('UTF-8')
        except:
            imgPub = None

        return JsonResponse({
            'titulo': objPub.titulo,
            'autor':f"{objPub.autorPub.first_name} {objPub.autorPub.last_name}",
            'descripcion':objPub.descripcion,
            'datosComentarios': datosComentarios,
            'imgPub':imgPub
        })
    except:
        return JsonResponse({
            'titulo':'SIN DATOS',
            'autor':'SIN DATOS',
            'descripcion':'SIN DATOS',
            'datosComentarios':None,
            'imgPub':None
        })
    
def publicarComentario(request):
    datosComentario = json.load(request)
    print(datosComentario)
    comentarioTexto = datosComentario.get('comentario')
    idPublicacion = datosComentario.get('idPublicacion')
    objPublicacion = publicacion.objects.get(id = idPublicacion)
    comentario.objects.create(
        descripcion = comentarioTexto,
        pubRel = objPublicacion,
        autoCom = request.user
    )
    return JsonResponse({
        'resp':'ok'
    })

def crearPublicacion(request):
    if request.method == 'POST':
        tituloPub = request.POST.get('tituloPub')
        descripcionPub = request.POST.get('descripcionPub')
        autorPub = request.user
        imagenPub = request.FILES.get('imagenPub')

        publicacion.objects.create(
            titulo = tituloPub,
            descripcion = descripcionPub,
            autorPub = autorPub,
            imagenPub = imagenPub
        )

        return HttpResponseRedirect(reverse('app3:informacionUsuario'))
    
def eliminarPublicacion(request):
    if request.method == 'POST':
        idPublication = request.POST.get('idPublication') 
        objPublicacion = publicacion.objects.get(id = idPublication) 
        if objPublicacion.imagenPub is not None:
            objPublicacion.imagenPub.delete(save = True)
        objPublicacion.delete()
        
        return HttpResponseRedirect(reverse('app3:informacionUsuario'))    
       
"""
PREGUNTA 1 - B
CREAR EL IF QUE PERMITA RECONOCER EL MÉTODO DE LA PETICION:
IF REQUEST.METHOD == ....
DENTRO DE LA SELECTIVA CAPTURAR LOS DATOS DEL FORMULARIO : 
USERNAMEUSUARIO = REQUEST.POST.GET('USE ...
...

CREAR EL OBJETO USER CON USERNAME E EMAIL : 

OBJUSR = USER.OBJECTS.CREATE(
    USERNAME = ... ,
    EMAIL = ... 
)

LUEGO SETEAR LA CONTRASEÑA CON LA FUNCION SET_PASSWORD:
CONTRAUSUARIO = REQUEST.POST.GET('CONTRAUSUARIO')
OBJUSR.SET_PASSWORD(CONTRAUSUARIO) ...

FINALMENTE CREAR EL REGISTRO EN DATOSUSUARIO Y RELACIONARLO CON EL
OBJETO OBJUSR - RECORDAR LA RELACION ONE TO ONE Y COMO SE CREO
EL USUARIO EN LA CLASES 5 Y 6

FINALMENTE REDIRECCIONAR A LA MISMA RUTA DE CONSOLAADMINISTRADOR - return HttpResponseRedirect(reverse('app3:consolaAdministrador'))

EJEMPLO DE CREACION DE NUEVO USUARIO:

usernameUsuario = request.POST.get('usernameUsuario')
contraUsuario = request.POST.get('contraUsuario')
nombreUsuario = request.POST.get('nombreUsuario')
apellidoUsuario = request.POST.get('apellidoUsuario')
emailUsuario = request.POST.get('emailUsuario')
profesionUsuario = request.POST.get('profesionUsuario')
nroCelular = request.POST.get('nroCelular')
perfilUsuario = request.POST.get('perfilUsuario')

nuevoUsuario = User.objects.create(
    username=usernameUsuario,
    email=emailUsuario
)
nuevoUsuario.set_password(contraUsuario)
nuevoUsuario.first_name = nombreUsuario
nuevoUsuario.last_name = apellidoUsuario
nuevoUsuario.is_staff = True
nuevoUsuario.save()


datosUsuario.objects.create(
    profesion=profesionUsuario,
    nroCelular=nroCelular,
    perfilUsuario=perfilUsuario,
    usrRel=nuevoUsuario
)

""" 
# -- Gestión de usuarios --

@login_required(login_url='/')
def consolaAdministrador(request):
    if request.method == 'POST':
        usernameUsuario = request.POST.get('usernameUsuario')
        contraUsuario = request.POST.get('contraUsuario')
        nombreUsuario = request.POST.get('nombreUsuario')
        apellidoUsuario = request.POST.get('apellidoUsuario')
        emailUsuario = request.POST.get('emailUsuario')
        profesionUsuario = request.POST.get('profesionUsuario')
        nroCelular = request.POST.get('nroCelular')
        perfilUsuario = request.POST.get('perfilUsuario')

        nuevoUsuario = User.objects.create(
            username=usernameUsuario,
            email=emailUsuario
        )
        
        nuevoUsuario.set_password(contraUsuario)
        nuevoUsuario.first_name = nombreUsuario
        nuevoUsuario.last_name = apellidoUsuario
        nuevoUsuario.is_staff = True
        nuevoUsuario.save()

        datosUsuario.objects.create(
            profesion = profesionUsuario,
            nroCelular = nroCelular,
            perfilUsuario = perfilUsuario,
            usrRel = nuevoUsuario
        )
        
    allUsers = User.objects.all().order_by('id')
    return render(request,'consolaAdministrador.html',{
        'allUsers':allUsers
    })

def obtenerDatosUsuario(request):
    """
    Pregunta 3
    Esta funcion devolvera los campos que se necesitan 
    cargar en la ventana modal para poder ser editados
    Con el id del usuario se puede obtener el objeto y devolver
    el objeto Json con la informacion necesaria.
    """
    idUsuario = request.GET.get('idUsuario')
    try:
        objUser = User.objects.get(id = idUsuario)
        objDatosUsuario = datosUsuario.objects.get(usrRel = objUser)
        return JsonResponse({
            'username': objUser.username,
            'nombre': objUser.first_name,
            'apellido': objUser.last_name,
            'profesion': objDatosUsuario.profesion,
            'email': objUser.email,
            'nroCelular': objDatosUsuario.nroCelular,
            'perfilUsuario': objDatosUsuario.perfilUsuario
        })
    except:
        return JsonResponse({
            'username': 'SIN DATOS',
            'nombre': 'SIN DATOS',
            'apellido': 'SIN DATOS',
            'profesion': 'SIN DATOS',
            'email': 'SIN DATOS',
            'nroCelular': 'SIN DATOS',
            'perfilUsuario': 'SIN DATOS'            
        })    


def actualizarUsuario(request):
    """
    Pregunta 5
    En esta funcion recibira los datos del formulario de actualizacion de usuario
    Debe capturar dichos datos, recuerde que en el input con atributo name idUsuario
    se ha cargado el id del usuario correspondiente lo que le permitira obtener el objeto
    de la base de datos. Con el objeto capturado modificar los campos respectivos y finalmente
    ejecutar el metodo save() para su respectiva actualizacion
    """
    if request.method == 'POST':
        idUsuario = request.POST.get('idUsuario')
        nombreUsuario = request.POST.get('nombreUsuario')
        apellidoUsuario = request.POST.get('apellidoUsuario')
        profesionUsuario = request.POST.get('profesionUsuario')
        nroCelular = request.POST.get('nroCelular')
        perfilUsuario = request.POST.get('perfilUsuario')
        
        objUser = User.objects.get(id = idUsuario)
        objDatosUsuario = datosUsuario.objects.get(usrRel = objUser)
        
        objUser.first_name = nombreUsuario
        objUser.last_name = apellidoUsuario
        objUser.save()
        
        objDatosUsuario.profesion = profesionUsuario
        objDatosUsuario.nroCelular = nroCelular
        objDatosUsuario.perfilUsuario = perfilUsuario
        objDatosUsuario.save()
   
        return HttpResponseRedirect(reverse('app3:consolaAdministrador'))

# -- Otros --

def ejemploJs(request):
    return render(request,'ejemploJs.html')

def devolverDatos(request):
    return JsonResponse(
        {
            'nombreCurso':'DesarroloWebPython',
            'horario':{
                'martes':'7-10',

app3/templates/ejemploJs.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Ejemplo Js</title>
        <script src="{% static 'js/ejemploJs.js' %}"></script>
    </head>
    <body>
        <h1 id="numeroEditar">0</h1>
        <div>
            <button onclick="incrementarNumero()">Incrementar</button>
            <button onclick="disminuirNumero()">Disminuir</button>
        </div>
        <div>
            <select id="valorNumero" onchange="cargarNumero()">
                <option value=""></option>
                <option value="25">25</option>
                <option value="35">35</option>
                <option value="45">45</option>
                <option value="55">55</option>
                <option value="65">65</option>
                <option value="75">75</option>
            </select>
            <input id="numSeleccionado" readonly>
            <button onclick="agregarNumero()">Agregar</button>
            <button onclick="actualizarSuma()">Sumar</button>
        </div>
        <br>
        <h4>Lista de numeros : </h4>
        <div>
            <ul id="listaNumeros">

            </ul>
        </div>
        <div>
            LA SUMA DE LOS ELEMENTOS ES : <i id="sumaFinal">SUMA</i>
        </div>
    </body>
</html>

app3/templates/informacionUsuario.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Vista de ingreso</title>
        <!--Importar bootstrap-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <!--Importar fontAwesome-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

        <!--Importar scripts de javascript-->
        <script src="{% static 'js/informacionUsuario.js' %}"></script>
    </head>
    <body>
        <div class="bg-primary">
            <div class="container">
                <div class="row justify-content-between align-items-center">
                    <div class="col-4 mt-3 mb-3 text-white">
                        <div class="row">
                            <h5>Bienvenido {{ user.first_name }} {{ user.last_name }}</h5>
                        </div>
                        <div class="row">
                            <h5 id="elMod">{{ user.datosusuario.profesion }}</h5>
                        </div>
                    </div>
                    <div class="col-1">
                        <a class="btn btn-success" href="{% url 'app3:cerrarSesion' %}"><i class="fa-solid fa-right-to-bracket"></i> Salir</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="container mt-3 mb-3">
            <div>
                <a href="{% url 'app3:consolaAdministrador' %}" class="btn btn-info">Panel de control <i class="fa-solid fa-arrow-right"></i></a>
            </div>
        </div>
        <div class="mt-5 text-center mb-3">
            <h1>Informacion del usuario : {{ user.first_name }} {{ user.last_name }}</h1>
        </div>
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-5 bg-light" style="border-radius: 20px;">
                    <div class="row mb-2 mt-2">
                        <div class="col-5">
                            <h5>Nombre completo : </h5>
                        </div>
                        <div class="col-7">
                            <i>{{ user.first_name }} {{ user.last_name }}</i>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-5">
                            <h5>Nombre de usuario : </h5>
                        </div>
                        <div class="col-7">
                            <i>{{ user.username }}</i>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-5">
                            <h5>Email : </h5>
                        </div>
                        <div class="col-7">
                            <i>{{ user.email }}</i>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-5">
                            <h5>Profesion del usuario : </h5>
                        </div>
                        <div class="col-7">
                            <i>{{ user.datosusuario.profesion }}</i>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-5">
                            <h5>Nro de celular : </h5>
                        </div>
                        <div class="col-7">
                            <i>{{ user.datosusuario.nroCelular }}</i>
                        </div>
                    </div>
                </div>
                <div class="col-5 bg-light h-100" style="border-radius: 20px;">
                    <div class="row mb-2 mt-2">
                        <div class="col-5">
                            <h5>Perfil : </h5>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-12">
                            <i>{{ user.datosusuario.perfilUsuario }}</i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mt-5 text-center mb-3">
            <h3>Publicaciones del usuario</h3>
        </div>
        <div class="container mt-5">
            <div class="row justify-content-between">
                <div class="col-2 text-start">
                    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#nuevaPub"><i class="fa-solid fa-calendar-plus"></i> Nueva publicacion</button>
                </div>
                <div class="col-2 text-end">
                    <a class="btn btn-success" href="#"><i class="fa-solid fa-download"></i> Descargar</a>
                </div>
            </div>
        </div>
        <div class="mt-5 container">
            <div class="row justify-content-center">
                <div class="col-8">
                    <table class="table table-bordered">
                        <thead class="table-dark">
                            <th>Autor</th>
                            <th>Titulo</th>
                            <th>Ver tweet</th>
                            <th>Eliminar</th>
                        </thead>
                        <tbody>
                            {% for pubInfo in allPubs %}
                            <tr>
                                <td>{{ pubInfo.autorPub.first_name }} {{ pubInfo.autorPub.last_name }}</td>
                                <td>{{ pubInfo.titulo }}</td>
                                <td><button data-bs-toggle="modal" data-bs-target="#detallePub" id="{{ pubInfo.id }}" onclick="cargarPub(this.id)" class="btn btn-info"><i class="fa-solid fa-eye"></i></button></td>
                                <td><button data-bs-toggle="modal" data-bs-target="#eliminarPub" id="{{ pubInfo.id }}" onclick="cargarEliminarPub(this.id)" class="btn btn-danger"><i class="fa-solid fa-trash"></i></button></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </body>
</html>

<!--Nueva Publicacion-->
<div class="modal fade" id="nuevaPub" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form method="post" action="{% url 'app3:crearPublicacion' %}" enctype="multipart/form-data">
            {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Crear publicacion</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-11">
                            <label>Titulo de la publicacion</label>
                            <input class="form-control" type="text" name="tituloPub" required>
                        </div>
                    </div>
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-11">
                            <label>Descripcion de la tarea</label>
                            <textarea class="form-control" type="text" required rows="4" name="descripcionPub"></textarea>
                        </div>
                    </div>
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-11">
                            <label>Subir foto</label>
                            <input class="form-control" type="file" name="imagenPub" required>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Registrar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!--Detalle publicacion-->
<div class="modal fade" id="detallePub" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Detalle de la publicacion</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h1 style="display: none;" id="idPublicacion"></h1>
                <div class="row form-group justify-content-around mb-3">
                    <div class="col-12">
                        <img id="imagenPub" style="max-width: 300px; display: none;">
                    </div>
                </div>
                <div class="row form-group justify-content-around mb-3">
                    <div class="col-8">
                        <label>Titulo</label>
                        <input class="form-control" type="text" readonly id="tituloPub">
                    </div>
                    <div class="col-4">
                        <label>Autor</label>
                        <input class="form-control" type="text" readonly id="autorPub">
                    </div>
                </div>
                <div class="row form-group justify-content-around mb-3">
                    <div class="col-12">
                        <label>Contenido de la publicacion</label>
                        <textarea class="form-control" type="text" rows="4" readonly id="descripcionPub"></textarea>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12" id="comentariosTotales">
                        <div class="row mb-3">
                            <div class="col-3">
                                Nombre Usuario
                            </div>
                            <div class="col-9">
                                Comentario realizado por un usuario
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-3">
                                Nombre Usuario
                            </div>
                            <div class="col-9">
                                Comentario realizado por un usuario
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-3">
                                Nombre Usuario
                            </div>
                            <div class="col-9">
                                Comentario realizado por un usuario
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row form-group justify-content-center">
                    <div class="col-10">
                        <input class="form-control" type="text" id="comentarioUsuario">
                    </div>
                    <div class="col-2">
                        <button class="btn btn-info" onclick="enviarComentario()">Comentar</button>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Eliminar Publicacion -->
<div class="modal fade" id="eliminarPub" tabindex="-1" role="dialog" data-bs-backdrop="static" data-bs-keyboard="false" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form method="post" action="{% url 'app3:eliminarPublicacion' %}">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Eliminar Publicación</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div style="display: none;">
						<input id="idPublication" name="idPublication" value="">
					</div>	
                    <div class="row justify-content-start">
                        <div class="col-3 text-center">
                            <i class="fa-solid fa-triangle-exclamation fa-5x" style="color: #dc3545;"></i>
                        </div>
                        <div class="col-9">
                            <p>¡Esta apunto de eliminar una publicación de forma permanente! ¡Se eliminarán todos comentarios publicados por los usuarios!</p>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success" data-bs-dismiss="modal">Cancelar</button>
                    <input type="submit" class="btn btn-danger" value="Eliminar">
                </div>                
            </form>
        </div>
    </div>
</div>

app3/templates/ingresoUsuario.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Vista de ingreso</title>
        <!--Importar bootstrap-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <!--Importar fontAwesome-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>
    <body>
        <div class="bg-light position-absolute start-50 top-50 translate-middle" style="height: 700px; width: 600px;">
            <div class="bg-light position-absolute start-50 top-50 translate-middle text-center" style="width: 300px; height: 550px;">
                <form method="post" action="{% url 'app3:ingresoUsuario' %}">
                    {% csrf_token %}
                    <img src="{% static 'img/logoApp.png' %}" width="100px" class="mb-3">
                    <div class="form-group mb-3">
                        <label>
                            Ingrese su nombre de usuario
                        </label>
                        <input class="form-control" type="text" name="nombreUsuario" placeholder="Username">
                    </div>
                    <div class="form-group mb-3">
                        <label>
                            Ingrese su password
                        </label>
                        <input class="form-control" type="password" name="contraUsuario" placeholder="Password">
                    </div>
                    <button type="submit" class="btn btn-primary mb-3"><i class="fa-solid fa-right-to-bracket"></i> Ingresar</button>
                    <img src="{% static 'img/logoPUCP.png' %}" width="300px">
                </form>
            </div>
        </div>
    </body>
</html>