app1/urls.py
from django.urls import path
from . import views

app_name='app1'

urlpatterns = [
    path('',views.hola,name='hola'),
    path('primerhtml',views.primerhtml,name='primerhtml'),
    path('segundohtml',views.segundohtml,name='segundohtml')
]

miPrimerProyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    path('',include('app3.urls'))
]

app1/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render
from django.http import HttpResponse, FileResponse, JsonResponse

# Create your views here.
def hola(request):
    return HttpResponse("Bienvenidos a mi web")

def primerhtml(request):
    nombre = "Martin"
    rol = 'USUARIO'
    apellido='Segovia'
    listaEstudiantes = [
        'Javier Hilario',
        'Dante Arroyo',
        'Jorge Ramirez',
        'Alexander Segovia'
    ]
    return render(request,'primerhtml.html',{
        'nombre':nombre,
        'rol':rol,
        'estudiantes':listaEstudiantes
    })

def segundohtml(request):
    nombre = "Alexander"
    return render(request,'segundohtml.html')

app1/templates/primerhtml.html
<!DOCTYPE html>
<html>
    <head>
        <title>Primer HTML</title>
    </head>
    <body>
        <h1>Bienvenido {{ nombre }}</h1>
        <h3>PUCP</h3>
        {% if rol == 'ADMIN' %}
        <div>
            ESTE ES UN ESPACIO PARA EL ADMINISTRADOR
        </div>
        {% endif %}
        <h2>Lista de estudiantes</h2>
        <ol>
            {% for estudiante in estudiantes %}
                <li>{{ estudiante }}</li>
            {% endfor %}
        </ol>
        <div>
            <a href="{% url 'app1:segundohtml' %}">Ir al SegundoHTML</a>
        </div>
    </body>
</html>

app1/templates/segundohtml.html
<!DOCTYPE html>
<html>
    <head>
        <title>Segundo HTML</title>
    </head>
    <body>
        <h1>Segundo HTML de la aplicacion</h1>
        <div>
            <a href="{% url 'app1:primerhtml' %}">Ir al PrimerHTML</a>
        </div>
    </body>
</html>